In [1]:
import pandas as pd

In [9]:
posts = pd.read_csv("Instagram Raw Data/Titans Instagram Posts Sep 6 '22 - Aug 21 '23.csv")
posts.drop_duplicates("timestamp").reset_index(drop=True, inplace=True)
posts

,timestamp,hashtags/0,hashtags/1,hashtags/2,hashtags/3,type,isSponsored,ownerUsername,productType,alt,caption,locationId,url,locationName,ownerId,displayUrl,likesCount,commentsCount,id,ownerFullName
0,2023-10-21T18:49:41.000Z,NaN,NaN,NaN,NaN,Image,False,titans,NaN,NaN,"Congratulations Coach Vrabel, the newest membe...",NaN,https://www.instagram.com/p/Cyq-h-hOZLG/,NaN,267761835,https://instagram.fgla3-2.fna.fbcdn.net/v/t51....,14243,144,3218659897465475782,Tennessee Titans
1,2023-10-15T16:09:22.000Z,NaN,NaN,NaN,NaN,Video,False,titans,clips,NaN,üôåüëëüôå\r\n‚Ä¢\r\nüì∫: @nflnetwork,3.792970e+08,https://www.instagram.com/p/CybPS3ZLXiO/,Tottenham Hotspur,267761835,https://instagram.fbog2-3.fna.fbcdn.net/v/t51....,7662,266,3214230026185439374,Tennessee Titans
2,2023-10-15T16:00:24.000Z,NaN,NaN,NaN,NaN,Sidecar,False,titans,NaN,NaN,SMB INT üîí\r\n‚Ä¢\r\nüì∫: @nflnetwork,3.792970e+08,https://www.instagram.com/p/CybOY0KLk6H/,Tottenham Hotspur,267761835,https://instagram.fvns1-2.fna.fbcdn.net/v/t51....,8921,151,3214226036982959751,Tennessee Titans
3,2023-10-15T16:40:17.000Z,NaN,NaN,NaN,NaN,Video,False,titans,clips,NaN,Spears has something special ‚ú® \r\n‚Ä¢\r\nüì∫: @nf...,3.792970e+08,https://www.instagram.com/p/CybS2oZLwpA/,Tottenham Hotspur,267761835,https://z-p4-instagram.fsgn5-8.fna.fbcdn.net/v...,15537,580,3214245678120110656,Tennessee Titans
4,2023-10-15T16:44:37.000Z,BALvsTEN,NaN,NaN,NaN,Image,False,titans,NaN,NaN,Final from London #BALvsTEN,NaN,https://www.instagram.com/p/CybTcwKL9Nv/,NaN,267761835,https://instagram.find2-1.fna.fbcdn.net/v/t51....,9067,1147,3214248297798554479,Tennessee Titans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,2022-09-19T23:22:39.000Z,NaN,NaN,NaN,NaN,Video,False,titans,clips,NaN,‚è∞‚öîÔ∏è,NaN,https://www.instagram.com/p/CitOAFEgiP4/,NaN,267761835,https://scontent-iad3-2.cdninstagram.com/v/t51...,5470,94,2931060510583563256,Tennessee Titans
957,2022-09-06T18:31:08.000Z,NaN,NaN,NaN,NaN,Video,False,nfllegacy,clips,NaN,Air McNair.,NaN,https://www.instagram.com/p/CiLOV31Dyrx/,NaN,4789363827,https://instagram.ffbm1-1.fna.fbcdn.net/v/t51....,65853,716,2921491858986052337,NFL Legacy
958,2022-09-11T23:31:02.000Z,NaN,NaN,NaN,NaN,Image,False,titans,NaN,NaN,‚òπÔ∏è\r\n\r\nPresented by @gatorade,NaN,https://www.instagram.com/p/CiYoyN-rrtT/,NaN,267761835,https://instagram.fman4-1.fna.fbcdn.net/v/t51....,18461,2362,2925267330821700435,Tennessee Titans
959,2022-09-11T20:46:03.000Z,NaN,NaN,NaN,NaN,Image,False,titans,NaN,NaN,First TD of the season ‚ÄºÔ∏è @d_hilliard26,9.457270e+14,https://www.instagram.com/p/CiYV56ApJyn/,Nissan Stadium,267761835,https://scontent-atl3-1.cdninstagram.com/v/t51...,5042,42,2925184296251858087,Tennessee Titans
960,2022-09-20T00:07:59.000Z,NaN,NaN,NaN,NaN,Sidecar,False,titans,NaN,NaN,First of the year for the üëë,NaN,https://www.instagram.com/p/CitTX4ILZAU/,NaN,267761835,https://instagram.fkep3-1.fna.fbcdn.net/v/t51....,13950,369,2931084136186482708,Tennessee Titans

In [10]:
len(posts)

961

In [11]:
posts.isnull().sum()

timestamp          0
hashtags/0       752
hashtags/1       945
hashtags/2       956
hashtags/3       957
type               0
isSponsored        0
ownerUsername      0
productType      538
alt              958
caption            3
locationId       529
url                0
locationName     529
ownerId            0
displayUrl         0
likesCount         0
commentsCount      0
id                 0
ownerFullName      0
dtype: int64

No need to drop any columns

In [17]:
posts.to_csv("Instagram Concatenated Data/Titans Instagram Posts", index=False)

In [13]:
comments1 = pd.read_csv("Instagram Raw Data/Titans Comments Posts 1-100.csv")
comments2 = pd.read_csv("Instagram Raw Data/Titans Comments Posts 101-200.csv")
comments3 = pd.read_csv("Instagram Raw Data/Titans Comments Posts 201-300.csv")
comments4 = pd.read_csv("Instagram Raw Data/Titans Comments Posts 301-400.csv")
comments5 = pd.read_csv("Instagram Raw Data/Titans Comments Posts 401-500.csv")
comments6 = pd.read_csv("Instagram Raw Data/Titans Comments Posts 501-600.csv")
comments7 = pd.read_csv("Instagram Raw Data/Titans Comments Posts 601-700.csv")
comments8 = pd.read_csv("Instagram Raw Data/Titans Comments Posts 701-800.csv")
comments9 = pd.read_csv("Instagram Raw Data/Titans Comments Posts 801-900.csv")
comments10 = pd.read_csv("Instagram Raw Data/Titans Comments Posts 901-961.csv")

In [14]:
comments_all = pd.concat([comments1, comments2, comments3, comments4, comments5, comments6, comments7, comments8, comments9, comments10], ignore_index=True)
comments_all.drop_duplicates(["timestamp", "text"]).reset_index(drop=True, inplace=True) 
comments_all

,text,id,likesCount,timestamp,postUrl,ownerUsername
0,Lets send a 2nd & 4th rd pick to Minnesota for...,18307960987117628,0,2023-10-16T17:01:27.000Z,https://www.instagram.com/p/CybTcwKL9Nv/,aka_j25since99
1,Trade @last_king_2 he doesn‚Äôt deserve to be ou...,17999166392184292,0,2023-10-16T17:09:03.000Z,https://www.instagram.com/p/CybTcwKL9Nv/,zach__sobel
2,If malik start against the falcons he going to...,18034473394594493,0,2023-10-16T17:27:25.000Z,https://www.instagram.com/p/CybTcwKL9Nv/,lil_aaaaaaaa
3,@cade.coleman Pete Carrol 2.0,18027994987643647,0,2023-10-16T18:40:22.000Z,https://www.instagram.com/p/CybTcwKL9Nv/,n8thegrubz
4,Bad year to be a Titans fan,18357617659073489,0,2023-10-16T21:05:23.000Z,https://www.instagram.com/p/CybTcwKL9Nv/,md11f_colt
...,...,...,...,...,...,...
27214,Told my wife if you guys lost this i‚Äôd be a bi...,17954215757092177,0,2022-09-14T22:26:56.000Z,https://www.instagram.com/p/CiYoyN-rrtT/,615codyg
27215,#53 Dylan Cole üóë asf how u miss that tackle an...,17922422417564121,0,2022-09-14T23:14:40.000Z,https://www.instagram.com/p/CiYoyN-rrtT/,sicario__556
27216,Should have been a easy win we couldn‚Äôt score ...,18040626607374308,0,2022-09-14T23:37:44.000Z,https://www.instagram.com/p/CiYoyN-rrtT/,deshaunlewis44
27217,Close game for my team Tennessee titans,17847980078838073,0,2022-09-16T07:45:19.000Z,https://www.instagram.com/p/CiYoyN-rrtT/,jayman.w36
27218,@i_x_mendoza yeah I get upset but I don't star...,17934140963451746,0,2022-09-16T15:41:16.000Z,https://www.instagram.com/p/CiYoyN-rrtT/,tbh_smd_bitch2.0

In [15]:
len(comments_all)

27219

In [16]:
comments_all.isnull().sum()

text             69
id                0
likesCount        0
timestamp         0
postUrl           0
ownerUsername     0
dtype: int64

In [18]:
comments_all.to_csv("Instagram Concatenated Data/Titans Instagram Comments", index=False)